# We need golang 1.16. I found this from docker hub
FROM golang:1.16-alpine

EXPOSE 8080

WORKDIR /usr/src/app

# Copy all of the content from the project to the image
COPY . .

# Building the project
RUN go build && \
adduser -S appuser
#rm -rf /usr/local/go

ENV GIN_MODE=release

USER appuser

# Executing the project
CMD ["./server"]