# We need ruby 3.0.0. I found this from docker hub
#FROM ruby:3.0.0
FROM ubuntu:18.04

# Exposing port 5000
EXPOSE 5000

# Setting working directory
WORKDIR /usr/src/app

# Copy all of the content from the project to the image
COPY . .

# Installing node
RUN apt-get update && \
apt-get install -y curl && \
curl -sL https://deb.nodesource.com/setup_14.x | bash && \
apt install -y nodejs && \

# Copy all of the content from the project to the image
#COPY . .

# Installing node packages
npm install && \
# Generating static files into build folder
npm run build && \
# Installing serve package
npm install -g serve && \
# Removing curl
apt-get purge -y --auto-remove curl && \
apt-get purge -y --auto-remove npm && \
#apt-get purge -y --auto-remove nodejs && \
rm -rf /var/lib/apt/lists/* && \
# Removing node

# Adding user
useradd -m appuser

# Changing to new user
USER appuser

# Command
CMD ["serve", "-s", "-l", "5000", "build"]